### ISSUE TITLE
OutOfRangeError (see above for traceback): FIFOQueue '_1_input/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)

### ISSUE THREAD

**Issue by irisliucy** [MenghanXia/InvertibleGrayscale#1]
Error found in training mode: 

```
Traceback (most recent call last):
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_input/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[{{node input/batch}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 336, in <module>
    train(train_list, val_list, debug_mode=False)
  File "main.py", line 156, in train
    _, loss, grads, vggs, orders = sess.run([train_op1, loss_op1, grads_loss, vgg_loss, global_order_loss])
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_input/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[node input/batch (defined at /home/chuiyiliu3/srv/InvertibleGrayscale/model.py:120) ]]

Caused by op 'input/batch', defined at:
  File "main.py", line 336, in <module>
    train(train_list, val_list, debug_mode=False)
  File "main.py", line 63, in train
    input_imgs, target_imgs, num = input_producer(train_list, in_channels, batch_size, need_shuffle=True)
  File "/home/chuiyiliu3/srv/InvertibleGrayscale/model.py", line 120, in input_producer
    in_batch, gt_batch = tf.train.batch([input, target], batch_size, num_threads=1, capacity=64)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 1019, in batch
    name=name)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 789, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/ops/data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3645, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/chuiyiliu3/srv/tf/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_input/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[node input/batch (defined at /home/chuiyiliu3/srv/InvertibleGrayscale/model.py:120) ]]

```

I had no problem with running in testing mode.

**Comment by irisliucy** [comment]
Problem solved by making sure input images' shape is identical to the network.

`tf.reshape(input, [shape_size, shape_size, channel])`

**Comment by Ars34lanaliawan34** [comment]
@MenghanXia 
How did you solve this problem because I'm facing this issue on testing from MSCOCO dataset where each image is of different size.

**Comment by Ars34lanaliawan34** [comment]
> 
> 
> Problem solved by making sure input images' shape is identical to the network.
> 
> `tf.reshape(input, [shape_size, shape_size, channel])`

where you used this function for setting shape because I'm facing same issue on testing dataset from MSCOCO
